export const Token = {
  PasswordHasher: "IPasswordHasher",
  TokenManager: "ITokenManager",
  EmailService: "IEmailService",
  StripeService: "IStripeService",
  GithubAuthService: "IGithubAuthService",

  PlanRepository: "IPlanRepository",
  UserRepository: "IUserRepository",
  SubscriptionRepository: "ISubscriptionRepository",
  CacheRepository: "ICacheRepository",
  OnboardingRepository: "IOnboardingRepository",
  CompanyRepository: "ICompanyRepository",
  WorkspaceRepository: "IWorkspaceRepository",
  WorkspaceRoleRepository: "IWorkspaceRoleRepository",

  PlanService: "IPlanService",
  AuthService: "IAuthService",
  SubscriptionService: "ISubscriptionService",
  UserService: "IUserService",
  StripeWebhookService: "IStripeWebhookService",
  VerifyService: "IVerifyService",
  OtpService: "IOtpService",
  PasswordService: "IPasswordService",
  OnboardingService: "IOnboardingService",
  CompanyService: "ICompanyService",
  WorkspaceService: "IWorkspaceService",
  PaymentService: "IPaymentService",

  VerifyController: "IVerifyController",
  PasswordController: "IPasswordController",
  OtpController: "IOtpController",
  PlanController: "IPlanController",
  AuthController: "IAuthController",
  SubscriptionController: "ISubscriptionController",
  UserController: "IUserController",
  StripeWebhookController: "IStripeWebhookController",
  OnboardingController: "IOnboardingController",
  PaymentController: "IPaymentController",
  CompanyController: "ICompanyController",
};
