export const Token = {
  PasswordHasher: "IPasswordHasher",
  TokenManager: "ITokenManager",
  EmailService: "IEmailService",
  StripeService: "IStripeService",
  GithubAuthService: "IGithubAuthService",

  PlanRepository: "IPlanRepository",
  UserRepository: "IUserRepository",
  SubscriptionRepository: "ISubscriptionRepository",
  CacheRepository: "ICacheRepository",
  OnboardingRepository: "IOnboardingRepository",
  CompanyRepository: "ICompanyRepository",
  WorkspaceRepository: "IWorkspaceRepository",
  WorkspaceRoleRepository: "IWorkspaceRoleRepository",
  WorkspaceMemberRepository: "IWorkspaceMemberRepository",
  WorkspaceInviteRepository: "IWorkspaceInviteRepository",
  WorkspaceTeamRepository: "IWorkspaceTeamRepository",

  PlanService: "IPlanService",
  AuthService: "IAuthService",
  SubscriptionService: "ISubscriptionService",
  UserService: "IUserService",
  StripeWebhookService: "IStripeWebhookService",
  VerifyService: "IVerifyService",
  OtpService: "IOtpService",
  PasswordService: "IPasswordService",
  OnboardingService: "IOnboardingService",
  CompanyService: "ICompanyService",
  WorkspaceService: "IWorkspaceService",
  PaymentService: "IPaymentService",
  WorkspaceRoleService: "IWorkspaceRoleService",
  WorkspaceInviteService: "IWorkspaceInviteService",
  WorkspaceMemberService: "IWorkspaceMemberService",
  WorkspaceTeamService: "IWorkspaceTeamService",

  VerifyController: "IVerifyController",
  PasswordController: "IPasswordController",
  OtpController: "IOtpController",
  PlanController: "IPlanController",
  AuthController: "IAuthController",
  SubscriptionController: "ISubscriptionController",
  UserController: "IUserController",
  StripeWebhookController: "IStripeWebhookController",
  OnboardingController: "IOnboardingController",
  PaymentController: "IPaymentController",
  CompanyController: "ICompanyController",
  WorkspaceController: "IWorkspaceController",
  WorkspaceRoleController: "IWorkspaceRoleController",
  WorkspaceInviteController: "IWorkspaceInviteController",
  WorkspaceMemberController: "IWorkspaceMemberController",
  WorkspaceTeamController: "IWorkspaceTeamController",
};
