services:
  api:
    build:
      context: .
      target: development
    command: npm run dev
    env_file:
      - .env
    ports:
      - "5000:5000"

    volumes:
      - .:/app
      - /app/node_modules
    
    depends_on:
      - redis

    restart: unless-stopped
  
  worker:
    build:
      context: .
      target: development
    
    command: npm run worker:dev

    env_file:
      - .env

    volumes:
      - .:/app
      - /app/node_modules

    depends_on:
      - redis

    restart: unless-stopped
  
  redis:
    image: redis:7-alpine

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data


volumes:
  redis-data: