services:
  elixir-api:
    image: gklme/elixir-api:latest

    command: npm run start

    env_file:
      - .env

    restart: unless-stopped

    networks:
      - apps-network
      - redis-network

  elixir-worker:
    image: gklme/elixir-api:latest

    command: npm run start:worker

    env_file:
      - .env

    restart: unless-stopped

    networks:
      - apps-network
      - redis-network

networks:
  apps-network:
    external: true
  redis-network:
    external: true
