services:
  app:
    build:
      context: .
      target: development
    ports:
     - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
    restart: always
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
