export const WORKSPACE_PERMISSIONS = {


  //members
  MEMBERS_INVITE: "members.invite",
  MEMBERS_REMOVE: "members.remove",
  MEMBERS_ROLE_UPDATE: "members.role.update",
  MEMBERS_VIEW: "members.view",

  //role
  ROLES_CREATE: "roles.create",
  ROLES_DELETE: "roles.delete",
  ROLES_UPDATE: "roles.update",
  ROLES_VIEW: "roles.view",

  //projects
  PROJECTS_CREATE: "projects.create",
  PROJECTS_DELETE: "projects.delete",
  PROJECTS_UPDATE: "projects.update",
  PROJECT_VIEW: "projects.view",

  //billing
  BILLING_VIEW: "billing.view",
  BILLING_MANAGE: "billing.manage",
} as const;

export type WORKSPACE_PERMISSION =
  (typeof WORKSPACE_PERMISSIONS)[keyof typeof WORKSPACE_PERMISSIONS];

export const BUILTIN_ROLES = {
  admin: [
    WORKSPACE_PERMISSIONS.MEMBERS_VIEW,
    WORKSPACE_PERMISSIONS.MEMBERS_INVITE,
    WORKSPACE_PERMISSIONS.MEMBERS_REMOVE,
    WORKSPACE_PERMISSIONS.MEMBERS_ROLE_UPDATE,
    WORKSPACE_PERMISSIONS.ROLES_VIEW,
    WORKSPACE_PERMISSIONS.ROLES_CREATE,
    WORKSPACE_PERMISSIONS.ROLES_UPDATE,
    WORKSPACE_PERMISSIONS.ROLES_DELETE,
    WORKSPACE_PERMISSIONS.PROJECTS_CREATE,
    WORKSPACE_PERMISSIONS.PROJECTS_DELETE,
    WORKSPACE_PERMISSIONS.PROJECTS_UPDATE,
    WORKSPACE_PERMISSIONS.PROJECT_VIEW,
    WORKSPACE_PERMISSIONS.BILLING_VIEW,
  ],
  member: [
    WORKSPACE_PERMISSIONS.MEMBERS_VIEW,
    WORKSPACE_PERMISSIONS.PROJECT_VIEW,
  ],
};

export const PERMISSION_DEPENDENCIES: Partial<
  Record<WORKSPACE_PERMISSION, WORKSPACE_PERMISSION[]>
> = {
  [WORKSPACE_PERMISSIONS.MEMBERS_INVITE]: [
    WORKSPACE_PERMISSIONS.MEMBERS_VIEW,
  ],
  [WORKSPACE_PERMISSIONS.MEMBERS_REMOVE]: [
    WORKSPACE_PERMISSIONS.MEMBERS_VIEW,
    WORKSPACE_PERMISSIONS.MEMBERS_INVITE,
  ],
  [WORKSPACE_PERMISSIONS.MEMBERS_ROLE_UPDATE]: [
    WORKSPACE_PERMISSIONS.MEMBERS_VIEW,
    WORKSPACE_PERMISSIONS.MEMBERS_INVITE,
  ],
  [WORKSPACE_PERMISSIONS.ROLES_DELETE]: [WORKSPACE_PERMISSIONS.ROLES_CREATE],
  [WORKSPACE_PERMISSIONS.ROLES_UPDATE]: [WORKSPACE_PERMISSIONS.ROLES_CREATE],
  [WORKSPACE_PERMISSIONS.ROLES_CREATE]: [WORKSPACE_PERMISSIONS.ROLES_VIEW],
  [WORKSPACE_PERMISSIONS.PROJECTS_DELETE]: [
    WORKSPACE_PERMISSIONS.PROJECTS_CREATE,
  ],
  [WORKSPACE_PERMISSIONS.PROJECTS_UPDATE]: [
    WORKSPACE_PERMISSIONS.PROJECTS_CREATE,
  ],
  [WORKSPACE_PERMISSIONS.PROJECTS_CREATE]: [WORKSPACE_PERMISSIONS.PROJECT_VIEW],
  [WORKSPACE_PERMISSIONS.BILLING_MANAGE]: [WORKSPACE_PERMISSIONS.BILLING_VIEW],
};
